### ISSUE TITLE
SquishIt.Framework IOException Unable to open file

### ISSUE THREAD

**Issue by MNF** [jetheredge/SquishIt#189]
We are using SquishIt in asp.net app, that is running on Window 2003 Server in production and Windows 7 developer machines without any problems. 
However when we installed it on window server 2008, we started to receive "Unable to open file" error (seems intermittently)

it would be useful if code of RetryableFileOpener.OpenTextStreamWriter will be change to provide more details about the error, i.e. String filePath, Int32 retry, Boolean append.
Looking in the code, it seems, that exception could happen only if retry<=0
The full error details are:
Type : System.IO.IOException, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
Message : Unable to open file
Source : SquishIt.Framework
Stack Trace :   at SquishIt.Framework.Files.RetryableFileOpener.OpenTextStreamWriter(String filePath, Int32 retry, Boolean append)
   at SquishIt.Framework.Files.FileWriterFactory.GetFileWriter(String file)
   at SquishIt.Framework.Renderers.FileRenderer.WriteFiles(String output, String outputFile)
   at SquishIt.Framework.Renderers.FileRenderer.Render(String content, String outputFile)
   at SquishIt.Framework.Base.BundleBase`1.RenderRelease(String key, String renderTo, IRenderer renderer)
   at SquishIt.Framework.Base.BundleBase`1.Render(String renderTo, String key, IRenderer renderer)
   at HomepageTabs.Page_Load(Object sender, EventArgs e)

Similar error reported in
http://groups.google.com/group/squishit/browse_thread/thread/d55f5c8f6c705c3d?pli=1 was resolved as “The folder I was trying to render the generated CSS to did not exist.”

**Comment by kipusoep** [comment]
Why doesn't SquishIt try to create the output directory if it doesn't exist?

**Comment by AlexCuse** [comment]
Because we don't want to create directories owned by the user the IIS process is running under.

**Comment by AlexCuse** [comment]
An argument could be made that such a feature would only be useful if you have a security issue as well.  Say you have an output directory like /Resources/Combined.  Typically you'd only want to grant write access to IIS_IUSRS group (or the user that your application pool runs under) for that folder, which requires it to exist.  But if you want the directory created, you'd need to grant write access to /Resources.  Or potentially anywhere that the server can map a path to.

**Comment by kipusoep** [comment]
Then I have a security 'issue', which I don't see as a security issue...
The application pool user needs write permissions in most of our websites, so why not 'try' to create an output folder and ignore any exceptions thrown while trying?

**Comment by AlexCuse** [comment]
If you want to create a separate issue I'd be glad to look at it once I get through some other things.  I don't have a ton of time to work on this stuff these days though, so it may be a while, my current priority is to get v1.0 ready by the end of the year.  Can always submit a PR also, though I am wondering if we'd have any problems running tests that interact with the file system on codebetter's CI server.

You can plug in your own renderer if it is really causing you pain, they are trivial to implement: https://github.com/jetheredge/SquishIt/blob/master/SquishIt.Framework/Renderers/FileRenderer.cs

Once written they can be used directly with bundles
````Bundle.JavaScript().WithReleaseFileRenderer(new DirectoryCreatingFileRenderer());````

or configured globally in global.asax.cs or elsewhere:
````SquishIt.Configuration.UseReleaseRenderer(new DirectoryCreatingFileRenderer());````
