### ISSUE TITLE
SquishIT breaks css calc() code.

### ISSUE THREAD

**Issue by getsetbro** [jetheredge/SquishIt#273]
SquishIT changes css "height: calc(100% - 50px);" to "height: calc(100%- 50px);" which breaks it. Notice the second one does not have a space after the percent sign.

**Comment by Squazz** [comment]
@AlexCuse  I still have this issue in both 0.9.6.1 & 0.9.8.2. is changing to YUI the "official" solution still?

**Comment by killair** [comment]
I have the same issue using 0.9.8.2 with calc(100%-
